# name: Build and deploy NestJS app to VPS - UyDev - GoodsDesignAPI

# on:
#   push:
#     branches: [ "main" ]
#   workflow_dispatch:

# jobs:
#   build:
#     name: Building image
#     runs-on: ubuntu-latest
#     steps:
#       - name: Checkout
#         uses: actions/checkout@v4

#       - name: Buildx
#         id: buildx
#         uses: docker/setup-buildx-action@v3
        
#       - name: DockerHub login
#         uses: docker/login-action@v3
#         with:
#           username: ${{ secrets.DOCKERHUB_USERNAME }}
#           password: ${{ secrets.DOCKERHUB_TOKEN }}
          
#       - name: Build and push NestJS application image
#         uses: docker/build-push-action@v5
#         with:
#           context: .
#           file: ./Dockerfile
#           push: true
#           tags: lequocuy/goodsdesignapi:latest
#           cache-from: type=gha
#           cache-to: type=gha,mode=max

#   migration:
#     name: Migration Database
#     runs-on: ubuntu-latest
#     needs: build
#     steps:
#       - name: Checkout repo
#         uses: actions/checkout@v3
#       - name: Setup Node
#         uses: actions/setup-node@v3
#       - name: Install dependencies
#         run: npm install --legacy-peer-deps
#       - name: Apply all pending migrations to the database
#         run:  npx prisma migrate deploy
#         # run: npx prisma migrate reset -f && npx prisma db seed
#         env:
#           DATABASE_URL: ${{ secrets.DATABASE_URL }}
  
#   deploy:
#     name: Deploying to VPS
#     runs-on: ubuntu-latest
#     needs: migration

#     steps:
#       - name: Deploy to VPS
#         uses: appleboy/ssh-action@v1.0.3
#         with:
#           host: ${{ secrets.SERVER_HOSTNAME }}
#           username: ${{ secrets.SERVER_USERNAME }}
#           password: ${{ secrets.SERVER_PASSWORD }}
#           script: |
#             cd /root/devops-vps/mono-repo
#             docker compose pull
#             docker compose up -d